### ISSUE TITLE
When using data-followCursor="true" the position of the tooltip is too far away from pointer.

### ISSUE THREAD

**Issue by Whateverinc** [atomiks/tippyjs#118]
![screen shot 2017-10-21 at 10 57 05 pm](https://user-images.githubusercontent.com/8814394/31858050-d657b578-b6b3-11e7-8881-33937a78ac6a.png)

The tooltip works fine when the data-followCursor is set to false, but once you enable it the position of the tooltip goes too far away from the pointer. 

Below is a demo of what the problem looks like. 

[https://codepen.io/divern/pen/xXerYb](https://codepen.io/divern/pen/xXerYb)

**Comment by atomiks** [comment]
Thanks for filing the issue. 

That distance was originally done because the cursor sometimes landed on the tooltip when it was moving fast, causing it to close. It usually works fine for regularly-sized tooltips, but for a large one like that positioned on the bottom, it will probably be an issue.

However I added `pointer: none` css to tooltips which means the tooltip won't interfere, so I will patch this up.

**Comment by atomiks** [comment]
`1.4.1`
