### ISSUE TITLE
Fit tippy to child of trigger

### ISSUE THREAD

**Issue by hirasso** [atomiks/tippyjs#129]
Hi there, first of all: Amazing work!

...I ran into an issue today: I want the trigger area for my tooltips to be bigger then the element the tooltip will fit to. Hope this explains what I mean:

![screenshot 2017-11-23 12 13 09](https://user-images.githubusercontent.com/869813/33170647-562eef88-d049-11e7-9ded-e6f62755f023.jpg)

Is there a way to achieve this with tippy?

**Comment by atomiks** [comment]
There's a couple ways. 

You could use an `offset` with negative Y value to move it closer to the asterisk element. However if it's interactive this will be problematic.

The second option is to `tippy()` that element instead of the trigger area, and add your own `mouseenter / focus` event listener to the trigger area and then call `.show()` on the tippy for the asterisk.

**Comment by hirasso** [comment]
@atomiks 
Thank you for your fast answer! I went with the second solution and it works fine. Are you thinking of ever introducing a new initialization argument for an element the tooltip should fit to? Would anything speak against this?

**Comment by atomiks** [comment]
I could probably be add it. 

What problems were you having? I forgot to mention you'd need the opposite event and then call `.hide()` as well, but that should be it.

**Comment by hirasso** [comment]
the problem I'm having is that the tooltip is interactive: The user should be able to click links on it. But when I `hide()` the tooltip on `mouseleave` of the red area, the tooltip gets hidden.

**Comment by atomiks** [comment]
Yeah there's some kinda complex custom code written for interactive tooltips that are triggered by mouseenter, which you'd need to replicate...

**Comment by hirasso** [comment]
Hehe, guessed something like this already 😉 
...so then a new option like described above would be a much cleaner way I think

**Comment by atomiks** [comment]
Indeed. Were you able to solve it though? I can help you if not

**Comment by hirasso** [comment]
Thats very nice of you! Haven't implemented it yet, but I think I'll be able to solve it with a `setTimeout()` on button `mouseleave` and `clearTimeout()` on tooltip `mouseenter`.

**Comment by atomiks** [comment]
The way it's done in the library is to temporarily bind a `mousemove` listener to the document inside the mouseleave listener and check if the `closest()` parent element of the event target element is a `.tippy-popper` (or the reference element itself).  If it is, don't hide the tooltip, otherwise do. 

However sometimes there's a tiny bit of space between the element and the popper (like 1px) due to imperfect rendering, so there's extra code to handle that (though it was originally designed for another option).

**Comment by hirasso** [comment]
Your approach also sounds good to me. My project isnt in production yet, do you already know if and when you will introduce my proposed new initialization option?

**Comment by hirasso** [comment]
OK, so this is what solved it for me:
```javascript
showTippy( el ) {
  el._tippy.show();
  $(document).mousemove((e) => {
    let isOverTooltip = $(e.target).closest('.tippy-popper').length
    let isOverHotArea = $(e.target).closest('.tooltip-hot-area').length
    if( !isOverTooltip && !isOverHotArea ) {
      el._tippy.hide()
      $(document).unbind('mousemove')
    }
  })
}
```
Thanks for your assistance! 🥇

**Comment by atomiks** [comment]
To avoid bloating the core, if it can be done in userland then it should be! 🎈
