### ISSUE TITLE
Binding to dynamically rendered elements?

### ISSUE THREAD

**Issue by Prnda1976** [atomiks/tippyjs#137]
I've been looking through tippy.js trying to find a way to have tips work on dynamically created html elements and I can't figure it out, or it does not exist. 

I have a page that is using SlickGrid which is a javascript library used to render tabular data with large number of rows. It does so by rendering only rows in the view port - the ones that are visible in the browser. The rest are rendered as the user scrolls up/down. You can see it in action here:

https://www.screencast.com/t/i9B9taoN

As you can see in this video, Tippy is bound correctly on the initial page load but once I scroll the page and come back to the same record the binding is gone. 

Is there a way to bind Tippy to dynamically created elements kind of like you can do in JQuery with "on":

`$("body").on("click", ".my-class", function(){ // implementation });`

**Comment by atomiks** [comment]
I can't view that video because of Flash 😢 

I'm assuming you mean event delegation? Not currently.

If SlickGrid has callbacks for when it creates or destroys rows, you can destroy/create the Tippy instances in there.

If the tooltips aren't working for the rows that were previously showing, then I assume it's creating brand new elements and not reusing the ones that were already created?

**Comment by Prnda1976** [comment]
@atomiks Yes that's what I mean. SlickGrid does destroy and recreate elements as they come into viewport.  This is one of the main reasons why it is so fast even when supplied with million rows of data - only elements in the viewport are rendered. It offers a few events that I could use to resolve this issues, namely onViewportChanged and onScroll but I think it would be a good idea to have some way to attach tippy behavior to dynamically generated elements regardless of the other libraries.

I used the tipsy.js library in the past and they were able to do it like this (using JQuery):

$('.class-selector').tipsy({ live: true });

Tipsy is far inferior in every other way to what you have created I'm just giving you this as an example...

**Comment by atomiks** [comment]
This is something that I definitely want to add 😄 

I'll see what I can do to implement it.

**Comment by Prnda1976** [comment]
@atomiks Awesome thank you!!!

**Comment by atomiks** [comment]
So I've been thinking about ways to implement this.

It seems that if we bind the event listeners to a parent element, we can't use `mouseenter` because that only fires when the mouse enters the element itself regardless of any child elements. We'd need to use `mouseover` instead.

So... our reference is the parent element, and perhaps the option name can be `target` which is a CSS selector string that matches the element you want to add the tooltip to (or the closest parent element of the event target, since it can have child elements too):

How is something like this?

```javascript
tippy(parent, {
  target: '.btn'
})
```

The Popper instances for each might be tricky but I'm sure I can work it out...

**Comment by Prnda1976** [comment]
@atomiks Sorry for the delayed response. Yes this seems reasonable as long as "parent" can be any element in the DOM hierarchy that is above the target element(s).

**Comment by rehfeldchris** [comment]
woot! I'm looking forward to this feature.

Nice job on the tippy so far.

**Comment by atomiks** [comment]
Check out #143 for the PR. 

It was actually fairly difficult to sort out the various bugs due to the different options (I thought it was simple, originally!)

I'm sure it's far from perfect still so will need more additional work but it's there if you want to clone/build the branch and test it out.

**Comment by atomiks** [comment]
`2.1.0`

**Comment by AntonioLule** [comment]
function tooltip_Edit(value){
  tippy('.edit-tippy',{
    interactive: 'true',
    trigger: 'click',
    theme: 'light-border',
    content:'<div class="col s12 m12 l12 xl12"><h3><b>Editar</b></h3></div>'+
            '<div class="input-field small col s12 m12 l12 xl12">'+
              '<input type="text" id="edit" value="'+ value +'" style="max-height: 40px;" />'+
            '</div>'+

            '<div style="display: flex; justify-content: space-around;">'+

              '<div class="col s6 m6 l6 xl6">'+
                '<button type="button" class="btn btn-primary btn-complete">Guardar</button>'+
              '</div>'+

              '<div class="col s6 m6 l6 xl6">'+
                '<h2><a href="#"><i class="fas fa-trash-alt" style="color:tomato"></i></a></h2>'+
              '</div>'+
            '</div>',
  }); 
}

//my var "value" it does not change with every click... HELP MY

**Comment by AntonioLule** [comment]
function tooltip_Edit(value){

  tippy('.edit-tippy',{
    interactive: 'true',
    trigger: 'click',
    theme: 'light-border',
    content:'<div class="col s12 m12 l12 xl12"><h3><b>Editar</b></h3></div>'+
            '<div class="input-field small col s12 m12 l12 xl12">'+
              '<input type="text" id="edit" value="'+ value +'" style="max-height: 40px;" />'+
            '</div>'+

            '<div style="display: flex; justify-content: space-around;">'+

              '<div class="col s6 m6 l6 xl6">'+
                '<button type="button" class="btn btn-primary btn-complete">Guardar</button>'+
              '</div>'+

              '<div class="col s6 m6 l6 xl6">'+
                '<h2><a href="#"><i class="fas fa-trash-alt" style="color:tomato"></i></a></h2>'+
              '</div>'+
            '</div>',
  
  }); 


}

/* my variable  "value"  does not change with every click */

**Comment by AntonioLule** [comment]
function tooltip_Edit(value){
  tippy('.edit-tippy',{
      content:  '<input type="text" id="edit" value="'+ value +'" style="max-height: 40px;" />'
 });
}
/*  my variable  does not change with every click. HELP ME PLEASE  */
