### ISSUE TITLE
Provide bower package

### ISSUE THREAD

**Issue by ivandotv** [atomiks/tippyjs#14]
I know that `bower` is kind of obsolete these days, but it would be great if you could provide a bower package.

**Comment by FezVrasta** [comment]
The problem with Bower is that you need to keep the compiled source code in the repository and it kinda sucks because it's difficult to manage the diffs.

I would suggest to use an approach similar to the one used by Popper.js, let Bower rely on `unpkg.com` (which serves files from npmjs.org).

Doing so, you could do:

```
bower install tooltip.js=https://unpkg.com/tippy.js --save
```

But at the moment, the `main` field of the `package.json` is an ESnext file and wouldn't work with Bower.

We first need to address #9 and provide an `.es5.js` bundle set as `main` field (alongside a `jsnext:main` field with the `es6` bundle)

**Comment by atomiks** [comment]
^ good points, don't think I'll provide a bower package for now.
