### ISSUE TITLE
Gradient dont work propertly and more

### ISSUE THREAD

**Issue by isfo** [atomiks/tippyjs#147]
I have configureed gradient like on example in https://atomiks.github.io/tippyjs/#features...
The tooltipo work nice, but appear a hell shadow over the component, i dont understand where it come.

And every time I call the tippy, it add a new elemet on source, take a loot this video:
https://youtu.be/bVhjWjuqKmU

**Comment by atomiks** [comment]
The problem there is you're setting the title attribute then creating a new tippy instance every time you hover over it. You should only be creating it once.

```js
if (!target._tippy) {
  tippy( ... ) // init tippy here
}
```

The "shadow" (I assume you mean the clipping that transitions?)  is because of the backdrop filling animation. Set `animateFill` to false. Since you've got the gradient on the entire background, if you wanted to use the filling animation then you'd need to put it on `.tippy-backdrop` instead.
