### ISSUE TITLE
Can't open show tooltip with show()

### ISSUE THREAD

**Issue by JamesJGoodwin** [atomiks/tippyjs#155]
According to [documentation](https://atomiks.github.io/tippyjs/#methods) I can init tippy popups and imidiately ask them to show. But something went wrong and it's impossible for me.

>Cannot read property 'show' of undefined

Here's my demo: https://jsfiddle.net/d1f8jm7e/

Am I doing right?

**Comment by atomiks** [comment]
The `_tippy` property is attached to the element itself. The object returned from `tippy` is not the instance itself, since the `tippy()` function can create multiple tooltips at once.

```js
const p = document.querySelector('p');
tippy(p, {
  placement: 'bottom',
  animation: 'perspective',
  arrowType: 'round',
  title: 'Hello, beauty',
  theme: 'light',
  arrow: true
});
p._tippy.show();
```

**Comment by coleherzer** [comment]
Hi there, 

I'm having an issue where `._tippy` seems to always be undefined when I go to access the Tippy methods. 

Here's my JS:
`    const tip_elem = document.querySelector('.tip-cart');

    tippy(tip_elem, {
        'arrow': true,
        'position': 'left',
        'trigger': 'click',
        'size': 'large',
        'interactive': true,
        'theme': 'light',
        'dynamicTitle': true
    });

    console.log(tip_elem._tippy) // returns undefined`

And here's my HTML:
`								<div class="ml-2 show mb-10 d-none">
									<button class="btn btn-success tip-cart" id="project-materials-order">
										<span>
											<i class="fa fa-shopping-cart"></i> View Cart (<span class="num-items">0</span>)
										</span>
									</button>
								</div>`

FYI: I'm using the 'dynamicTitle' option in an attempt to be able to dynamically update the title attribute on the tippy element, since I'm using tippy as a a shopping cart here (need to add content to the tip as user adds products to their order). 'dynamicTitle' doesn't seem to be doing the trick, but I'm hoping if I can get `._tippy` I can figure things out.

Any advice/help would be greatly appreciated. Thank you!

**Comment by atomiks** [comment]
@coleherzer are you on v3 or v2? This issue only applies to v2

Please post the full code, what you wrote works fine in a CodePen.

**Comment by coleherzer** [comment]
Oh geez. So sorry @atomiks .. Looks like I still had the v2 JS files from a couple months ago.

Thanks so much for your help though. Seems to be working well now.
