### ISSUE TITLE
disable focus on interactive popover

### ISSUE THREAD

**Issue by fenyagg** [atomiks/tippyjs#170]
Please add option to disable it
`if (options.interactive && elementIsInViewport(reference)) {
								popper.focus();
							}`

**Comment by atomiks** [comment]
Just curious, why would you want it disabled? (It's there for accessibility reasons)

**Comment by fenyagg** [comment]
I have a problem when:
1. large heigh html template
2. position right or left
3. trigger mouseenter
4. interactive

After open tooltip, if the tooltip is outside the screen (top or bottom), the window scroll. And the tooltip closes. 
screenshot example http://joxi.ru/5mdx4NIkWZMVm1

**Comment by atomiks** [comment]
That's helpful, could you upload a video too? (I get what you're saying, I just like seeing it live visually).

**Comment by atomiks** [comment]
Thanks! I think instead of disabling focus, we could save the current scroll position, focus it, then immediately set the scroll back to the saved position. That should still allow it to be focused, but keep it accessible

I will test it out.

**Comment by fenyagg** [comment]
Thanks for the quick fix. Why then need a focus if not scroll ?)

**Comment by atomiks** [comment]
Please check the PR: #173 and make sure it 100% fixes it. I tested it and it worked for my case, but need to make sure.

>Why then need a focus if not scroll ?)

Because you can still tab to elements within the interactive popper, it just won't scroll to it if it's not in the viewport. This is mainly important for screenreaders, etc, so they won't need to be looking at it. It's not 100% ideal but I think for the vast majority of cases, it's fine

**Comment by atomiks** [comment]
`2.1.1`

If you want to scroll to the popper if it's out of view, you can do it smoothly within the `onShown()` callback (probably only for `focus/click` trigger. I think that's better than an instant jarring jump due to the focus anyway.
