### ISSUE TITLE
Input focus/click tooltip disappears immediately after showing

### ISSUE THREAD

**Issue by michorvath** [atomiks/tippyjs#184]
I am using tippy on my form inputs. If I set the trigger to 'focus' the tips show and hide correctly via keyboard navigation, but if you click on the input, the tip shows and immediately disappears. Is this how it is supposed to work or a bug? I tried setting up manual focus/click triggers but then the tip is shown twice due to the nature of a click event.

**Comment by atomiks** [comment]
`hideOnClick: false`

**Comment by chhuang** [comment]
With `hideOnClick: false` on, how can I hide the popper when clicking outside?

**Comment by atomiks** [comment]
If it's on an input, then you should be using `focus` trigger, in which case clicking off will fire a `blur` event and hide it (except on iOS I think)

**Comment by ArielGueta** [comment]
The problem is when you have nested poppers. Imagine that you have the following structure:

Button with a `click` trigger opens a popper. Inside the popper, we have `input` that opens another `interactive` popper with the `focus` trigger.

Now, if you'll lose focus and click on the level two popper, you can't close the child popper until you focus again on the input.
