### ISSUE TITLE
Persistent tooltips

### ISSUE THREAD

**Issue by bsboris** [atomiks/tippyjs#19]
Hello,

When using `trigger: 'click'` and `hideOnClick: false`, is there any way to prevent tooltip from closing when clicked outside of tooltip?

Thanks for the great library by the way!

**Comment by atomiks** [comment]
`hideOnClick` is for clicking on the tooltipped element itself, but yeah tooltips close when clicking anywhere else. I'll have to add an option for that in the next release

**Comment by atomiks** [comment]
Just wondering: you still want the toggle functionality for the click, correct? 

I've modified the `hideOnClick` setting so that clicking on `mouseenter` tooltipped elements won't close the tooltip, along with clicking anywhere else on the document. But for click triggers it should still be able to toggle show/hide when clicking the element itself, or is that not what you want?

**Comment by bsboris** [comment]
Wow, thank you for the quick reply!

Actually, I want to implement user education feature, tooltips open manually on page load and user should explicitly click "close" button to hide tooltip. So, `click` triggers should not toggle tooltips in my particular use case, but I'm not sure if this will be correct behaviour for the library. I guess, both ways are OK.

**Comment by atomiks** [comment]
Hmm yeah, for the library I think the toggle functionality should remain, but I'm sure you can implement a way to disable the toggle maybe with `pointer-events: none` or something until they've closed it

**Comment by bsboris** [comment]
Yes, that would be great 👍

**Comment by atomiks** [comment]
Cool, I released it as 0.3.5 https://github.com/atomiks/tippyjs/releases/tag/v0.3.5

Let me know how it goes

**Comment by bsboris** [comment]
This is so awesome! Thank you 😁
