### ISSUE TITLE
A chunk of the tooltip appears when touchHold is true on the mobile screen

### ISSUE THREAD

**Issue by Tainan404** [atomiks/tippyjs#220]
This bug is difficult to reproduce, it only happens on mobile device. When touchHold is true and you tap the button the tooltip appears for a few milliseconds and disappears.

![lib-bug](https://user-images.githubusercontent.com/15806883/38560585-5544082c-3cac-11e8-9808-150ac0be70f6.gif)

[Pen](https://codepen.io/tainan404/pen/bvzmLy)

**Comment by Tainan404** [comment]
android chrome v65

**Comment by atomiks** [comment]
Not seeing anything wrong on Browserstack... you touch and hold the element and the tooltip will open, if you release it will hide. That's expected behavior.

**Comment by Tainan404** [comment]
As you can see in the give above if you have the ´touchHold´ as true and you just 'tap' the button, the tooltip will partially show for a few ms.

In the gif you can see the 'h d' showing above the Touch & Hold button when I just tap it.

**Comment by atomiks** [comment]
I've noticed issues with the `clip-path` transition on browsers unfortunately, it works perfectly on desktop browsers but for some reason on mobile ones it struggles (probably because it's not performant to animate, but there's no other option to prevent the tooltip content from overflowing the backdrop that I can think of).

If you add a delay, that should prevent a single tap from showing the tooltip, no?

**Comment by Tainan404** [comment]
The delay did not work for me.

**Comment by atomiks** [comment]
Going to remove the `clip-path` property/transition in the next patch due to some additional reported problems on mobile Chrome.
