### ISSUE TITLE
Tippy on new element added dynamically in the DOM

### ISSUE THREAD

**Issue by jfborfiga** [atomiks/tippyjs#267]
Hi,

I can't initiate tippy on new element added dynamically in the DOM.

Codepen here:
https://codepen.io/julienwangchang/pen/RBodpb

I have tried to use parent initialization also but it is not working.

Could you advise please ?

Thanks in advance.

**Comment by atomiks** [comment]
The problem is that `tippy()` needs the `title` attribute to be present, but it's been removed from the btn on the first call. So, when you go to clone it, the clone has no title, so calling tippy won't do anything.

You need to store the original clone somewhere and clone that: https://codepen.io/julienwangchang/pen/RBodpb?editors=0010
