### ISSUE TITLE
v3 Questions/Thoughts

### ISSUE THREAD

**Issue by davemoore24** [atomiks/tippyjs#275]
First, great work! I am currently using v2 in a production env and it makes working with popper so much easier. I pulled v3 and am actually replacing all menus, context menus, sub-menus in context menus and had a few questions... I know my use cases are not so much simple tooltips...
1. It would be great to have the ability for Tippy to return a promises (easier) or observables for the callbacks. What I am really looking for is the ability to get a promise from onShow/onHide... do logic ie. save to server, in a promise in which I could return to execute the onShown/onHidden.
2. I saw there was the `wait` callback in v2, not in v3. I tried it in v2 and wasn't too sure what it did or how it was suppose to work. I assume you got rid of this with the new `set` method. 
3. You should consider exposing your `hideAllPoppers` method as static on tippy as the software I am working on has years of `stopPropagation` all over the place which sucks... right now I just copied it.
3. Note - it seems in v3 the window.tippy.defaults are the default even after I use the new `setDefaults`... but each instance is correct... not sure if this has been noted or is by design.
4. Focusing... I noticed in v2 that when the menu was shown, the popper element would receive focus and in v3 it does not now. I have `ally` true which states the reference element can receive focus.... again, this would seem to be default for standard tooltips... not context menus, etc... 

- thanks
dm

**Comment by atomiks** [comment]
Thank you for the feedback.

1. Can you explain how that might work? The callbacks are lifecycle functions rather than methods, so I'm not sure how they would work with promises

2. This is a legacy thing from way back when the project was first started as a request to integrate with view libraries, I really don't know if it needs to exist anymore (probably not). I made some component wrappers which work with them without using it, but they're not perfect

3. Agree, not sure why I haven't yet

4. This is a bug. It changes the object reference but the static object refers to the old one still, I'll fix it.

5. Hmm, probably because of this: `lastTriggerEvent.type === 'focus'` -- it only focuses the popper if they're using keyboard navigation. I did this to minimize problems with the scrolling jumping around if they're using a mouse device (although, I seemingly fixed that with a hackish method of scrolling to the previous position after the focus).

I'll release a new alpha version today. It fixes some long standing problems, and a couple bugs I noticed.

**Comment by davemoore24** [comment]
Wow. That was fast. Thanks for the release as Im pulling it now. 
Regarding 1... I thought about it more and your right. I think I have such a unique use case... ie. Im using this in Angular 6 and also in a historic GWT application... all of my headaches are in GWT, not Angular. Unlike the new JS frameworks that make data binding and managing DOM element painless, GWT is just the opposite in which I run into race conditions with Tippy (not tippy, GWT's issues)... so that is why I was thinking it would sweet to have either promises.

The real issue I am trying to solve is the in GWT I need to internally call (attach/detach) for child "widgets" to react to... I was removing GWT click handlers in favor of having Tippy just add them... but the result of not using a manual trigger is there isn't anything like a onBeforeShow/onBeforeHide events or better yet a promise, mainly to solve GWT's race conditions for attaching/detaching DOM elements because on outside or body clicks... `hide()` executes faster then the GWT event loop.... 

But... no worries on this as this is a rare use case since GWT is pretty much obsolete. Thanks again for the quick reply and release. There are a lot of fans of your work at my company.
