### ISSUE TITLE
Tippy not work correctly

### ISSUE THREAD

**Issue by KiarashS** [atomiks/tippyjs#301]
Dear,

First thanks for Tippy!
I used tippy in a project that worked properly until several days ago but suddenly failed! Please see below image!

`<script src="https://unpkg.com/tippy.js/dist/tippy.all.min.js"></script>`

![tippy](https://user-images.githubusercontent.com/1054134/45946673-762c1900-bffe-11e8-9454-9fab5386e645.png)

**Comment by atomiks** [comment]
It's because `@latest` is now on v3 which is a breaking change.

The docs linked a specific version for the CDN throughout the entirety of v2 to prevent the CDN from breaking, so you must have removed the version which will cause things to break when a new major version gets published. 

Place `@2` after `tippy.js` to use the latest of v2:

```js
<script src="https://unpkg.com/tippy.js@2/dist/tippy.all.min.js"></script>
```
