### ISSUE TITLE
Docs potentially need updating to specify that `data-tippy-content` is sometimes needed, rather than just `data-tippy`

### ISSUE THREAD

**Issue by josephrocca** [atomiks/tippyjs#306]
In the docs, under the `Method 1: Auto` heading, there should perhaps be a small note saying that if you write something like `tippy(".my-class")` then it won't work if those `my-class` elements just have the `data-tippy` attribute. That attribute seems to only work on page load. So it seems you need to use `data-tippy-content` if you're applying tippy to elements that are dynamically generated.

[Here's an example](http://jsbin.com/pukijenedo/1/edit?html,output) that doesn't work unless you change `data-tippy` to `data-tippy-content`.

Thanks for the great lib! And can I just say, your docs page is super sleek 👌

**Comment by darrensw777** [comment]
This should be reopened and perhaps a section on dynamic creation added to the docs? I've just spent hours on this and such a simple fix.

Something under Method 1 along the lines of:

If you are adding elements dynamically and they show the tooltip but with no content, use `data-tippy-content` instead of `data-tippy`

**Comment by darrensw777** [comment]
I think the help section is perfect now, explains it clearly. Thanks!
