### ISSUE TITLE
Automated tests?

### ISSUE THREAD

**Issue by FezVrasta** [atomiks/tippyjs#31]
I would like to discontinue Tooltip.js and point users here, but I'm not confident since this project doesn't have any automated tests.

Is it something you are considering to add?

**Comment by atomiks** [comment]
Yes it is.. since the project was new there was so much to change/fix up and features to add but I think it's settling now, so I can start adding automated tests.

**Comment by atomiks** [comment]
I'll get around to this one day I promise 🤣

**Comment by mdesantis** [comment]
In the meantime I want to thank you for this library, I :heart: it!

**Comment by atomiks** [comment]
@mdesantis I appreciate it! It's my first little library I made and wasn't even expecting people to use it so much. Not exactly the most experienced when it comes to managing things like this.

I think once I have automated tests set up and everything passes, I can release v1.0.0

**Comment by atomiks** [comment]
I've begun to refactor everything into individual units and have started writing some tests for a v1.0.0 release 😋 

- cleaning up the API since so many features were kinda haphazardly added as dev went along
- since it's a factory function, it will change to a lowercase `tippy` instead of `Tippy` (was kept uppercase for backwards compat for this using `new Tippy`)
- possible feature to use SVG as the tooltip & anime.js integration? These are extremely cool-
 https://tympanus.net/Development/TooltipAnimations/

**Comment by atomiks** [comment]
`v1.0.0` I wrote a lot of tests but tons more need to be written, lots of stuff was fixed/changed up. Will continue working later.

**Comment by atomiks** [comment]
Travis is now set up thanks to @artyomtrityak, more tests need to be written in due time.
