### ISSUE TITLE
~500ms delay before tooltip show

### ISSUE THREAD

**Issue by makeitrein** [atomiks/tippyjs#330]
Hello! tippyjs has been a great addition to my side project, https://ficdb.com/

On the home page, Ficdb has a list of fanfics, each with a list of genres. Hovering over a genre reveals a tooltip explaining what the genre is. Feel free to test it out now!

I've noticed that there is a strange pause before the tooltip shows up, so I used the performance tool in Chrome's inspector which showed the following:

<img width="341" alt="screen shot 2018-10-19 at 11 38 16 pm" src="https://user-images.githubusercontent.com/2068463/47252367-4d7a2200-d3f8-11e8-9d0b-76b898924c76.png">

**getOffsetParent** is the expensive call here, taking up to 500ms to recalculate style on the web page. This is with `"tippy.js": "^3.0.6"` initialized by the following code:

```
const main = () => {
    tippy.setDefaults({
        arrow: true,
        arrowType: 'round',
        animation:"fade",
    })

    tippy('[data-tippy-content]')
}
```

I've been browsing through Tippyjs's and Popper.js's Github issues and haven't found any concrete suggestions yet on what I should try doing to speed things up - what would you guys recommend?

Many thx for open sourcing!
~ makeitrein

**Comment by atomiks** [comment]
Using 6x CPU slowdown in devtools and hovering around on the docs page, I'm not seeing any performance problems, but doing the same on your page shows some severe problems.

Are you sure you don't have any code that could be impacting the performance, like code in `onShow` or such?

**Comment by atomiks** [comment]
Toggling the `border` property on one of the grid items on the page takes like 600ms+. There seems to be a problem with the complexity of the page layout which is causing performance problems. A single reflow takes a long time, but that's not really the fault of this lib because it's necessary for position calculations, etc. 

Maybe try to remove different properties to see what's causing the issue. Facebook's feed can have tons of nodes w/o problems
