### ISSUE TITLE
Can't use in multiple dynamic contents

### ISSUE THREAD

**Issue by bilalmalkoc** [atomiks/tippyjs#349]
https://codepen.io/wpuzman/pen/mQeeRQ

Tooltip shows only first content. Is possible to make it dynamic?

**Comment by KubaJastrz** [comment]
This issue is not related in any way to `tippy` package.

Your problem lays in this line:
```js
content: document.querySelector('.tooltip-content').cloneNode(true)
```
You are reading content from first occurence of `.tooltip-content`, that's why it feels like it's not _dynamic_.

If you want more help, please read appropriate docs for jQuery or [vanilla JS](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) first and/or post this in StackOverflow.

**Comment by bilalmalkoc** [comment]
I also tried `content: $(this).find('.tooltip-content'),` but same. It shows `[object object]`

**Comment by bilalmalkoc** [comment]
Thank you. It works now :)
