### ISSUE TITLE
Is it possible to prevent position update?

### ISSUE THREAD

**Issue by barthisrael** [atomiks/tippyjs#351]
I've read the docs and found a **livePlacement** property. It seemed to be what I needed but didn't work as I expected. When my page loads and the tippy instance is shown, if I scroll down the page in such a way the tippy gets hidden in the top, it starts to flip infinitely between top and bottom position of the reference element.

**Comment by atomiks** [comment]
Can you create a CodePen of the issue?

`livePlacement` disables Popper.js scroll listeners when showing but will update the position on each new show().

**Comment by barthisrael** [comment]
Hello,

Sure, sorry about the delay.
**CodePen**: https://codepen.io/barthisrael/pen/wQgdyw

I've also attached a MP4 screen video of what is going on here.

[tippy-demo-2018-11-13_10.36.16.zip](https://github.com/atomiks/tippyjs/files/2576239/tippy-demo-2018-11-13_10.36.16.zip)

Thanks in advance.

**Comment by atomiks** [comment]
Thank you for the repro! The problem is `sticky: true`. It will update the popper's position on each animation frame. If you remove that option, the `livePlacement` option works as expected.

I believe however, we can improve the behavior and dynamically change the popper instance's `flip` modifier instead of disabling scroll listeners. I'll look into it

**Comment by barthisrael** [comment]
Hello!

Sorry for the delay, again. I succeeded with `sticky: false`. Thanks a lot!
