### ISSUE TITLE
Shape problem when arrow is false

### ISSUE THREAD

**Issue by bilalmalkoc** [atomiks/tippyjs#352]
When disabling arrow, it's shape breaks. Is that other way to disable arrow? Or is it an issue?
https://codepen.io/wpuzman/pen/mQeeRQ

**Comment by bilalmalkoc** [comment]
`animateFill: false` is works.

**Comment by atomiks** [comment]
The `animateFill` effect is only meant to be used on small-ish regular text tooltips because it has some limitations.

In V2 there was a `clip-path` transition and a different approach to it, but it caused some problems (stuttering + isn't performant to animate) on mobile browsers, and wasn't supported on IE11/Edge.

> Weird thing is that .tippy-backdrop is not rendering when arrow is present, however.

This has always been the case because of the nature of the animation, there is `overflow: hidden` on the tooltip which prevents the arrow element from being visible outside it

**Comment by atomiks** [comment]
I'm wontfixing this for now. If anyone has better ideas for the backdrop you can create a PR for it!
