### ISSUE TITLE
Trying to design like this arrow but I dont have any success

### ISSUE THREAD

**Issue by alinoudev** [atomiks/tippyjs#357]
![selection_048](https://user-images.githubusercontent.com/21170850/48753961-cac3db80-ecb1-11e8-8735-ab73fc512649.png)

Pen is at https://codepen.io/qau-mana/pen/jQaZVw

**Comment by alinoudev** [comment]
solved the issue at https://codepen.io/anon/pen/qQVoVN if anyone need helps in the future

**Comment by atomiks** [comment]
I've noticed some inherent problems (transform stacking context + fact that scale makes the 1px border thicker undesirably) with `arrowTransform` and a border theme. I will probably be removing the option next major due to this.

But you can still create that large arrow like so:

EDIT: nvm you beat me to it!
