### ISSUE TITLE
Enabling interactive option makes scrollable container jump when popover is closing

### ISSUE THREAD

**Issue by Cyrus-d** [atomiks/tippyjs#388]
I have a target element that is inside a scrollable container. when popover is visible and parent container scrolled, closing popover will cause the container to jump.

To simulate the problem please refer to the codepen link and follow the instructions:

Template: [https://codepen.io/Cyrus80/pen/PdpxyK?editors=1111](https://codepen.io/Cyrus80/pen/PdpxyK?editors=1111)

1. click on the button to make popover visible
2. scroll container while popover is open.
3. click anywhere on the page to close the popover. at this point, the container will jump.

Thanks,

**Comment by atomiks** [comment]
It's because the reference re-receives focus which makes the container scroll back up to show it to the user again.

One solution would be to cache the scroll position `onHide`, then in a `setTimeout` call, scroll the container back to its original position.

```js
  onHide() {
    const { scrollLeft, scrollTop } = container;
    requestAnimationFrame(() => {
      container.scrollLeft = scrollLeft;
      container.scrollTop = scrollTop;
    });
  }
```

`requestAnimationFrame` is pretty hackish but works without a "jitter" unlike `setTimeout`. 

I was going to add more control to interactive focus to the user by allowing them to manually control it in the next version. I might work on it soon.

**Comment by atomiks** [comment]
It's because the reference re-receives focus which makes the container scroll back up to show it to the user again.

One solution would be to cache the scroll position `onHide`, then in a `requestAnimationFrame` call, scroll the container back to its original position.

```js
  onHide() {
    const { scrollLeft, scrollTop } = container;
    requestAnimationFrame(() => {
      container.scrollLeft = scrollLeft;
      container.scrollTop = scrollTop;
    });
  }
```

https://codepen.io/anon/pen/MZErOP

`requestAnimationFrame` is pretty hackish but works without a "jitter" unlike `setTimeout`. 

I was going to add more control to interactive focus to the user by allowing them to manually control it in the next version. I might work on it soon.

**Comment by Cyrus-d** [comment]
thanks for the explanation, I did think to cache the scroll position, however, it needs more works when reference is in nested parents with the scrollbar.

So after you have explained the cause of the problem, it got me thinking why not just hide the element for a moment:

```
  onHide() {
    referenceElement.style.visibility = 'hidden';
    requestAnimationFrame(() => {
      referenceElement.style.visibility = 'visible';
    });
  }
```
it does work fine, but i am not sure if may couse other problems! could you please give me you thoght on this.

thanks,

**Comment by atomiks** [comment]
Interesting, I thought the browser would still scroll to it if invisible. As long as there are no flickers it seems fine.

The scroll position cache trick is already applied but only works for the window level (not inside scrolling containers).

**Comment by Cyrus-d** [comment]
unfortunatly it does flicker in the edge, so I will apply toggle visibility only when the element is not overflown and is visible. (no need for toggling visibility if the element is visible, scrollbar won't jump)

I also did try recursive parents position caching but it will make the scrollbar jump back and forward, didn't look nice. 

I am closing this issue as the workaround works for me.

Thanks for the help and suggestions ;)
