### ISSUE TITLE
Using "Template linking", if template contains nested tippy elements - they not works

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#435]
From examples:
```
<button data-template="one">One</button>
<template id="one">
  <strong>Content for `one`</strong>
  <button data-template="nested">Nested in One</button>
</template>

<template id="nested">
  <strong>Content for `nested in one`</strong>
</template>
```

This initialization code will not affect selectors in the template content.
```
tippy('button', {
  content(reference) {
    const id = reference.getAttribute('data-template')
    const container = document.createElement('div')
    const linkedTemplate = document.getElementById(id)
    const node = document.importNode(linkedTemplate.content, true)
    container.appendChild(node)
    return container
  },
})
```

Demo with problem: https://codepen.io/7iomka/pen/jJbjGW?editors=1010
Question: how to make this to work?
I want to make multi-level expandable menu.

**Comment by atomiks** [comment]
The problem is the nested `<button>` isn't seen by tippy, since the content within any `<template>` is "inert" and doesn't get rendered on the page. You should be able to use divs instead

**Comment by Armanio** [comment]
Hi @7iomka 
It happens because you add new button in runtime but you don't reinitialize tippy
Of course i might be wrong, i hope @atomiks will correct me

But if i'm right, you must be observe new DOM nodes and reinitialize tippy tooltips.
For example you can use [MutationObserver](MutationObserver) API like this:
https://codepen.io/armanio/pen/morPPy

**Comment by atomiks** [comment]
I guess that's one way to do it @Armanio ! Especially if you want to keep using `<template>`
