### ISSUE TITLE
disableAll and enableAll (feature request)

### ISSUE THREAD

**Issue by richardbushell** [atomiks/tippyjs#442]
Please add:-

disableAll()
enableAll()

This would be great for disabling and enabling ALL the poppers (on-demand), especially useful for one-page website apps, and for things like SVG USE statements, etc...

**Comment by atomiks** [comment]
You can do this in userland easily:

```js
function setEnabled(value) {
  [...document.all].forEach(node => {
    if (node._tippy) {
      node._tippy[value ? 'enable' : 'disable']()
    }
  })
}

tippy.enableAll = setEnabled.bind(null, true)
tippy.disableAll = setEnabled.bind(null, false)
```

**Comment by atomiks** [comment]
You can do this in userland easily:

```js
function invokeMethodForAll(method) {
  [...document.all].forEach(node => {
    if (node._tippy) {
      node._tippy[method]()
    }
  })
}

tippy.enableAll = () => invokeMethodForAll('enable')
tippy.disableAll = () => invokeMethodForAll('disable')

```

**Comment by richardbushell** [comment]
Thanks, yes I had already implemented this using forEach, but I was just suggesting it as a built-in method going forward, like hideAll()

**Comment by atomiks** [comment]
Well `hideAll` includes an internal check that makes it harder to for users to implement. `group` is possible to implement outside but figured it would be better built-in since it's a little complex.

I'm going to avoid adding (easy) features to core if they can be implemented by users without much trouble, to avoid increasing bundle size. Thanks for the request though 🙂

**Comment by KubaJastrz** [comment]
This could be added to something like Recipes section in the docs, so it's easier to find.
