### ISSUE TITLE
Max-width 350px

### ISSUE THREAD

**Issue by richardbushell** [atomiks/tippyjs#451]
I cannot understand the logic for hard-wiring a 350px max-width? Why is this included?

I had to override it in v3, and now again in v4, but I simply don't understand the logic for including it. When using em's for font-sizes then on larger monitor resolutions then the tooltips simply get truncated mid-word. Why include a hard-wired pixel value at all?

**Comment by atomiks** [comment]
By default usually you don't want the tooltip to be overly wide. With default browser settings it seems to work fine.

In your case with custom em font sizes then it makes sense to override it with something custom.

**Comment by richardbushell** [comment]
If you wanted to keep this, wouldn't it make sense to use a relative character based width unit anyway such as em, rather than px? Or even vw?

**Comment by atomiks** [comment]
Many of the other options (number values) use `px` since that's what positioning is based on. The CSS uses `rem` though.

If I were to change the default it would be `"22rem"` instead

Though I'm wondering what situation would cause text to be cut off at 350px wide, is the font huge? that's long enough for many characters o.O

**Comment by richardbushell** [comment]
Most web designers tackling responsive layout would change the base rem/em sizing using @media queries depending on the screen size/width. See our example here:-

https://living.video
(just choose Select A Map Area) then TIPPY is used on the subsequent two slides.

If you think a Tooltip should have a default max-width of say 30 chars, then it would make sense to use 30em (i.e. 30 x an uppercase M)

**Comment by atomiks** [comment]
That's an interesting case since it's valid that the tooltips would size proportionally with the screen resolution. I don't think that is very common though. 

I noticed you're doing:

```css
.tippy-tooltip.living-theme {
  max-width: none !important;
}
```

You can set the default maxWidth like this before initializing tooltips:

```js
tippy.setDefaults({ maxWidth: '' })
```

I don't think it's too difficult to override the default behavior so gonna close this one out

**Comment by fnick851** [comment]
@atomiks 
How do I call `setDefaults` if I am using tippyjs-react?

**Comment by sengiv** [comment]
updating @atomiks's answer

**DEPRECATED**
`tippy.setDefaults({ maxWidth: '30em' })`

**WORKING VERSION**
`tippy.setDefaultProps({ maxWidth: '30em' })`
