### ISSUE TITLE
Interactivity doesn't work without HTML content "beneath" the tooltip

### ISSUE THREAD

**Issue by fractaledmind** [atomiks/tippyjs#468]
If you simply fork the bug template and add `interactive: true`, you will struggle to select the text in the tooltip: https://codepen.io/smargh/pen/XQVPyO

However, if you place some sort of content "beneath" the tooltip (wherever it ends up being positioned), then the interactivity functions as expected: https://codepen.io/smargh/pen/WWdgPd

**Comment by atomiks** [comment]
This is because the `<body>` element has a `mouseleave` listener on it, and by default it doesn't stretch the entirety of the window. 

It's intentional to prevent interactive tooltips from staying visible on the page when the cursor leaves the document (in Safari only I think, which is why it's not on the `document` instead) if the reference element or the tippy was near the document boundary.

So it's a wontfix, but the fix is to use `html, body { height: 100%; }`

**Comment by fractaledmind** [comment]
Ah. Understandable. Thank you for the clear and concise explanation.

PS. Wonderful library and a pleasure to use.
