### ISSUE TITLE
Interactive and followCursor allow tooltip to be moved from within tooltip

### ISSUE THREAD

**Issue by fractaledmind** [atomiks/tippyjs#469]
If you set both `interactive: true` and `followCursor: 'horizontal'`, when your mouse enters into the tooltip, you can still move the tooltip: https://codepen.io/smargh/pen/vMpzMK

It would make more sense to me if `followCursor` only applied when the cursor was moving within the tooltip parent, not the tooltip itself.

**Comment by atomiks** [comment]
`followCursor` and `interactive` don't aren't really meant to be used together.

**Comment by atomiks** [comment]
`followCursor` and `interactive` aren't really meant to be used together

**Comment by atomiks** [comment]
That was before we gained the `horizontal` and `vertical` options though, 😅 . Because the cursor was moving away from the cursor at the same rate it moved, and you can't make it interactive since it doesn't make sense obviously. 

I guess it should be possible in these two scenarios. `initial` already works fine.
