### ISSUE TITLE
Unable to click on inner html of interactive tooltip

### ISSUE THREAD

**Issue by bmwatson214** [atomiks/tippyjs#475]
I am trying to programmatically close my popover using an interactive tooltip. I need this to be done on click of a specific element, not the entire popover, because I want to execute additional logic with an ajax call after the click. It seems that the parent element `id="tippy-1"` is covering the children from being interacted with? 

Am I misunderstanding the documentation or is this a bug?

Here is a demo of the problem: https://codepen.io/bbecker/pen/XQBLrB

In the coderpen, I am trying to log a console message when the "CLOSE" element is clicked, however, it seems that the outermost tippy element is all that is clickable.

**Comment by atomiks** [comment]
In v2, the string value `html: "#..."` clones an element on the document, but you're adding the listeners to the element on the document, not the one inside the tippy itself.

Also, try to upgrade to the latest major version (v4) if possible, since that's what the docs reflect, and this issue tracker is only really for the latest version since the old ones are unmaintained. The latest docs are quite a bit better now and this issue most likely wouldn't have happened with the newest version. 

Hope this helps 🙂

**Comment by bmwatson214** [comment]
Ahh, I see! That makes sense. 

I upgraded to v4 and things are looking good. Thank you so much for your help!

**Comment by RedTemi** [comment]
HI could you explain if its not too much exactly what you did..?
