### ISSUE TITLE
Auto-initialization(data-tippy) animation with other themes

### ISSUE THREAD

**Issue by AsafeToschi** [atomiks/tippyjs#477]
I really enjoyed the Auto-initialization( **data-tippy="..."** ) animation, have some way to use it with the light theme? 
If so, it would be a great idea to include it in the animation options.

**Comment by atomiks** [comment]
What do you mean "auto-initialization" animation? That's just the default animation that manual initialization has as well. And the light theme has it as well, `data-tippy-theme="light"`

**Comment by AsafeToschi** [comment]
First Case - This animation has some kind of wave, remembers me the ripple effect

![WhatsApp Image 2019-04-24 at 22 49 52](https://user-images.githubusercontent.com/47419233/56704680-74394e00-66e4-11e9-8a55-f91f5a4231e6.jpeg)
![chrome-capture](https://user-images.githubusercontent.com/47419233/56705197-65ec3180-66e6-11e9-88ef-c3ef73c39617.gif)

________________
Second Case - That is just a shift away

![WhatsApp Image 2019-04-24 at 22 50 15](https://user-images.githubusercontent.com/47419233/56705269-a8ae0980-66e6-11e9-8797-3102eb2f07a7.jpeg)
![chrome-capture](https://user-images.githubusercontent.com/47419233/56705282-b4013500-66e6-11e9-91a6-aa8dad32e8b1.gif)

**Comment by atomiks** [comment]
Ah yeah, the filling effect is not possible with the arrow currently (and I was disabling it since the very first version v0.1.0 😛), because the tooltip needs `overflow: hidden` to clip the backdrop shape, but the arrow is a separate element so the tooltip can't have that overflow property.

I'm assuming it _might_ be possible using some clipping technique with SVG, but I haven't really investigated it and it might take up too much code to be worth it.

**Comment by AsafeToschi** [comment]
oh got it haha
Thanks for taking this question and the awesome lib!
