### ISSUE TITLE
tooltip embedded in link of background element, touch triggers link on mobile instead of tooltip

### ISSUE THREAD

**Issue by overwerk** [atomiks/tippyjs#516]
Hi,

I'd like create a tooltip on a label that is embedded in a link.
Works fine on non-touch devices. Touch devices trigger the link instead of showing the tooltip first and after a second click the link is followed (like in cases where the tooltip object is a link itself).

Example: https://output.jsbin.com/fatuladige/
I'm unable to see the tooltip on mobile, because every time a touch the label the link is triggered.

Is there any solution for this?

Thanks in advance! :-)

**Comment by atomiks** [comment]
Hi,

You can either:

1. Add a click listener to the span and call `event.preventDefault()` and use `hideOnClick: false` option

or

2. Use `touchHold: true` for different behavior on touch devices that doesn't require a full tap to show the tippy

or

3. Move the element outside of the link and use positioning to move it into the right place

or

4. Consider a different UI for this problem

**Comment by KubaJastrz** [comment]
Making a tooltip on hover is not a very good UX on mobile. While on desktops it Just Works™ because users hover over links before clicking them (or tab with keyboard), on mobile you don't have this middle step between seeing a link and clicking on it.

I would suggest making a separate target element next to the link that is visible on mobile so users can have the tooltip working properly.
