### ISSUE TITLE
dont create if content is null

### ISSUE THREAD

**Issue by evazzadeh** [atomiks/tippyjs#526]
Sometimes content is null or false or empty. in this conditions we can't say to tippy please don't draw :|

https://codepen.io/evazzadeh/pen/orWZbx

**Comment by atomiks** [comment]
You can use a selector for elements where the content is guaranteed instead, instead of an encompassing one like `button` where the element might not have a tippy.

**Comment by atomiks** [comment]
The reason I don't want to do this is because in the past, I've been confused why the tippy isn't showing when I forgot to give it content. It's better to show the contentless tippy to remind you than not to create it at all. It's up to you to ensure the instance always has content. You can also return `false` from `onShow()` if it doesn't have content.

**Comment by evazzadeh** [comment]
At least you can check for false or undefined and in normal condition this value is not created. that means if user want to do not show tippy, return false or undefined.

for example we use title attr of element to show tippy and sometimes title is empty, we can change selector but it's better to fix it on definition of tippy.
