### ISSUE TITLE
interactive tooltip inside interactive tooltip

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#539]
I have a situation where i need a user to select something from the tooltip of a tooltip, and i want to keep the first tooltip open when the user clicks inside the second tooltip :)

Here's a pen using tippyjs v5 👍 :

https://codepen.io/wyzix33/pen/bPyMdL

I tried using ```hideOnClick: false``` and it kind of works, i've made the logic to hide it if click is outside any of the tooltips, but i'm wandering if it will be better when using interactive tooltips to keep them all open when click is inside any of the tooltips. 

Or maybe there is a better solution i'm not seeing it...

Thanks

**Comment by atomiks** [comment]
This (and especially hovering instead of clicking regarding interactive nested popovers) is kind of a missing piece of this lib right now.  It needs a good API/solution that I haven't thought of yet.  Custom logic seems like the right idea for now.

**Comment by atomiks** [comment]
So this actually works properly in v5 now due to the default `appendTo: "parent"` behavior.

However, sub-tippys:

- **The width can be messed up**: due to the `max-width: calc(100% - 5px)` on `.tippy-popper` (for small viewport widths) its width matches the width of the subpopper
- **Can be cut off:** when `arrow: false`, `overflow: hidden` cuts it off when there is no arrow.

I'll see how these can be fixed in a backwards-compatible manner.

**Comment by atomiks** [comment]
Another problem is the "hit target" area for hover menus. Starting from the cursor point, an imaginary triangle is formed from it to the tippy where the tippy won't hide.

This will be the most complex part to get right, I made some rough draft:

<img src="https://i.imgur.com/gZ0Rqwd.png" height="350" />

Also this would probably be a plugin since it would add a lot of code, and require this? https://stackoverflow.com/questions/2049582/how-to-determine-if-a-point-is-in-a-2d-triangle

`interactiveBorder` is effectively a simplified version of this, and nowhere near as good for UX.

**Comment by atomiks** [comment]
This should be properly supported now
