### ISSUE TITLE
embedding video elements in a tippy causes the closed caption menu to appear in the wrong place

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#565]
## Bug description
When a `<video>` element is in a tippy, the closed caption menu appears in the wrong location:

<img width="588" alt="Screen Shot 2019-08-26 at 12 30 28 PM" src="https://user-images.githubusercontent.com/718067/63717530-5a785680-c7fd-11e9-9a92-c6700abde063.png">

This has to do with setting css transform on the tippy element. When I embed a `<video>` tag in a pure popper.js, and set `gpuAcceleration` to `false`, the popper does not set a css `transform` on the popper element, and the video menu looks right. I've tried disabling `gpuAcceleration` as an option that gets passed to popper from the tippy config, but this doesn't work, because tippy still has css that declares a transform.

Would love to find a way around this, as the present situation makes it impossible to embed accessible video elements in a tippy.

**Comment by atomiks** [comment]
CodePen demo? 

If you mean the transform CSS, it's only a 10px offset so I don't understand how the captions are so far away in that example?

**Comment by atomiks** [comment]
Managed to make a demo myself, and replicated what you said. Just setting `transform: translate(0px)` causes the problem. In my case, the menu doesn't appear at all. That seems like a browser bug to me which you could file to Chromium.

In v5 this problem doesn't exist since we no longer set a `transform` for the visible state for the animations. For v4 as a workaround, you'd probably need to set `distance: 20` and remove the transforms in the CSS yourself by overriding/unsetting the styles. This can't be patched for the current major since it's a breaking change

**Comment by mreinstein** [comment]
> CodePen demo

Sorry, I should have put one together. The issue isn't so much the amount of transform, it has to do with the fact that a transform is specified at all. (It changes it's positioning to be fixed.)

> That seems like a browser bug to me which you could file to Chromium.

It is indeed! This is the bug that I was looking at prior to filing the issue on tippy:

https://bugs.chromium.org/p/chromium/issues/detail?id=895453&q=component%3ABlink%3EMedia%3EControls&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

That bug also mentions a blog post describing the underlying problem: 

https://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/
It

> In v5 this problem doesn't exist since we no longer set a transform for the visible state for the animations

Ah, ok. I'll close this issue then.

Thanks for taking a look!
