### ISSUE TITLE
You need to increase "tippy-backdrop / state=visible" Scale from "1" to "1.1"

### ISSUE THREAD

**Issue by dschiller** [atomiks/tippyjs#566]
## Bug description

A Tooltip like this looks ugly because it's ufinished:

```
tippy('#sidebarItemFeatures', { placement: 'left', role: 'sidebar', distance: '0px', content: '<div class="tooltip-left"><strong>Features</strong><br/><br/>Features are used to<br/>describe a Software<br/>Product<br/><br/>Open <span class="tooltipShortcut">CTRL+E, F</span></div>'});
```

## Reproduction

https://codepen.io/dirk-teichmann/pen/MWgmmLa

**Comment by atomiks** [comment]
This is a long wontfix issue because the we can't determine the dimensions of the tooltip with CSS only and scale the backdrop element appropriately w/o JS logic (which adds bloat). `scale(1.1)` only solves that particular dimension -- if you make the tooltip even taller, it won't fill it unless you use an even larger scale.

The effect is meant to be used for simple small tooltips only, so set `animateFill: false` for any html-based dynamic content. In v5, it won't be default anymore and opt-in to reduce confusion.
