### ISSUE TITLE
What is the issue when using offset and interactive together?

### ISSUE THREAD

**Issue by codTango** [atomiks/tippyjs#567]
My main use case is that users will be able to do interactive actions on the tooltip, and from the UX prospective, I'd like to set some offset on the tooltip. But I read the doc mentions that avoid using them together. So what's the issue around that? Also, is there a plan to fix the issue?

https://atomiks.github.io/tippyjs/all-options/
referring to the offset description.

**Comment by atomiks** [comment]
If using a `number` instead of `string` for offset (horizontal for vertical placements, and vertical for horizontal placements) there shouldn't any problems - it's when you try to use offset on the same axis (e.g. vertical offset for vertical placements) that there's a problem due to the way interactivity works. 

For this type of offset on the same axis, prefer `distance` instead. This is due to which elements are being translated. This should be clarified properly on the docs.

**Comment by codTango** [comment]
@atomiks Thanks for clarify this out, after looking at doc of Popper.js and some examples, now I find a way to make the offset working for my particular use case.

But I think it's still a little bit unclear on how `offset` would work when using with `interactive` for others, maybe it's nice to have some examples to demonstrate it.
