### ISSUE TITLE
Aurelia: Update Tippy instance options

### ISSUE THREAD

**Issue by rowellx68** [atomiks/tippyjs#58]
Is there a way to update the options of a tippy instance?

I've tried creating another instance of tippy with the new options and referencing the same element and it still doesn't work.

I've also tried destroying the previous tooltip and creating a new one and no dice.

**Comment by atomiks** [comment]
You'd have to make a new instance yes

Can you make a codepen that shows destroying the tooltip then creating a new instance doesn't apply the new settings?

**Comment by rowellx68** [comment]
Right. Unfortunately I'm using tippy with Aurelia, so I can't really put it up on Codepen.

If you want to look, [here's](https://github.com/rowellx68/aurelia-ts-webpack-skeleton/blob/19413efca9f9bbce56972ef3168bdd983c5d1d56/src/attributes/tooltip.ts) the code. It might be because of how I'm importing it.

**Comment by atomiks** [comment]
I think I know what the problem is. I believe it's because the `title` gets removed from the element, so when you make a new instance, there's no title to apply the tooltip...

The previous title is stored in the attribute `data-original-title` (like Bootstrap), so you might want to do el.setAttribute('title', el.getAttribute('data-original-title')) or something... or just reapply the title however.

https://codepen.io/anon/pen/eRJemr

**Comment by rowellx68** [comment]
Thats was it! It now works like magic.

[aurelia custom attribute](https://github.com/rowellx68/aurelia-ts-webpack-skeleton/blob/7332eca53d68bd90bb24d26392c39d4cb124528b/src/attributes/tooltip.ts)
[tippy.js type definition](https://github.com/rowellx68/aurelia-ts-webpack-skeleton/blob/master/custom_typings/tippy.d.ts)

**Comment by atomiks** [comment]
Forgot to mention in `0.17.0` (says in release notes) this now breaks since the `data-original-title` is removed on destroy. The title is restored on destroy now so you don't need re-set the title.
