### ISSUE TITLE
Position Sticky + Overflow hidden + Intervactive true breaks the tooltip

### ISSUE THREAD

**Issue by sporto** [atomiks/tippyjs#602]
Hi, we just came across this combination of factors in our app that breaks the tooltip.

## Bug description

If you have a container with

```
.container {
  position: sticky;
  overflow: hidden;
}
```

And ` interactive: true` 
Then the tooltip doesn't show. Removing any of these three things makes the tooltip work fine.

## Reproduction

https://jsbin.com/guhegeh/2/edit?html,css,console,output

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/issues/600#issuecomment-539962365

**Comment by atomiks** [comment]
I don't know if `positionFixed: true` can be set by default for interactive tippys - if there are unwanted side effects when not inside `position: fixed` (e.g. absolute or sticky). Otherwise, to avoid this scenario, that would be good to set as default so people don't encounter this issue.

I've added it to migration guide, FAQ, and all props on the website with the 2 solutions.
