### ISSUE TITLE
Don't know how to import Tippy.js 5.0.3 inside of angular.json

### ISSUE THREAD

**Issue by TGotwig** [atomiks/tippyjs#614]
Hello there 🤗

I could successfully import Tippy.js `4.3.5` inside of `angular.json` as follows:
```
"scripts": [
  "node_modules/popper.js/dist/umd/popper.min.js",
  "node_modules/tippy.js/umd/index.all.min.js"
]
```
But I don't know how I should do this with Tippy.js `5.0.3`,
I tried some things out but nothing worked 🤷‍♂

**Comment by atomiks** [comment]
Shouldn't you be importing `tippy` per "component"? Aren't those global scripts?

**Comment by atomiks** [comment]
Also note that treeshaking and code splitting don't work with `iife`, so you're including extra bloat. Plus since it's a global script, the routes/components that don't use `tippy` will still load it for the user when it doesn't need to be.

Stick with `import` syntax and only require it when necessary (if possible).

**Comment by TGotwig** [comment]
Ahh yeah that works, thanks 😊👍
