### ISSUE TITLE
v5: How to show tip on selected text?

### ISSUE THREAD

**Issue by tedypranolo** [atomiks/tippyjs#623]
I am trying to show a tip exactly on the selected textnode instead of the parentElement. What is the proper way to do this with v5? (If possible with sticky:true).
I have tried passing a placeholder element and overriding `getClientBoundingRect `with `window.getSelection().getRangeAt(0).getBoundingClientRect` but it doesn't seem to work.

**Comment by KubaJastrz** [comment]
Interesting problem. Here's something I threw together. Use at your own risk 😉 

https://codepen.io/hawking/pen/NWWgwWr

**Comment by atomiks** [comment]
@KubaJastrz there seems to be a bug when clicking off the selection again, the tippy "re-shows" when the selection goes away. Can be fixed by wrapping the `mouseup` logic in `setTimeout` but there's prob a better solution there.

Also would benefit from `inlinePositioning` but that uses `onTrigger` and bypasses `.show()` (which has exposed a bug, actually).

**Comment by tedypranolo** [comment]
This works well. Thank you @KubaJastrz and @atomiks

**Comment by z0xyz** [comment]
@atomiks Is @KubaJastrz's solution is the only viable solution for this use-case?
