### ISSUE TITLE
tippy.js

### ISSUE THREAD

**Issue by hexabyte23** [atomiks/tippyjs#633]
I am looking for a way to install manually CSS and JS of tippy. When I unzip source.zip, there is no /dist dir or equiv. Where should i find a tippy.css & tippy.js minify that not refer to /src ?

**Comment by atomiks** [comment]
https://unpkg.com/tippy.js@5/ allows you to browse through the dist files.

However, manually installing JS and CSS is not recommended because you lose versioning management that the unpkg CDN or npm/Yarn provide. You don't receive fix/feat updates easily and will lag behind the website documentation, among other issues, and this quickly becomes an unmaintainable way to manage dependencies.

Some reading:
https://stackoverflow.com/a/31930422/9470278
https://softwareengineering.stackexchange.com/a/372495

**Comment by ffd8** [comment]
Is it currently possible (v6) to grab the necessary file from unpgk for basic offline including of the script? Started using this last year by simply attaching 'tippy.all.js' and 'popper.min.js' (no NPM or CDN) and it worked great for projects that could run in offline mode (using CDN if online accessed). Curious if one of the files in /dist includes this (tried a few but failed) or a tool you can suggest to package this myself while pointing to the CDN. While it makes total sense what you mentioned above for best practice in importing.. for archive reasons etc, seems useful to have 3rd install option of downloading ~2 needed files.

**Comment by xtlc** [comment]
I would also be interested in this!

**Comment by markcst** [comment]
So, no way this could be locally installed, as we can already do with Bootstrap, or Popper, or other libs/framework?
From the downloaded GitHub zip, which file of it should we import in an html?
