### ISSUE TITLE
Tippy ignores plugins' "onShow" lifecycle hook returning false.

### ISSUE THREAD

**Issue by some-sam** [atomiks/tippyjs#644]
## Bug description

If a plugin's lifecycle hook for "onShow" returns false, it is ignored and the tip is shown anyway. This seems unexpected.

## Suggestion

Fixing this would be rather tricky, as there can be some ambiguous cases (one plugin returning false, another not, etc).  I suggest updating the "lifecycle" docs to denote that returning false from a plugin has no effect.

## Workaround

My workaround is to override the `onShow` prop in `onCreate`. Please let me know if this seems reasonable and future-proof:

```
    const myPluginThatSometimesCancelsShow = {
        fn: function() {
            return {
                onCreate: function(instance) {
                    const origOnShow = instance.props.onShow;
                    instance.props.onShow = function(){
                        if ( /* some internal logic */ ) { return false; }
                        if (origOnShow) return origOnShow();
                    }
                },
            }
        }
    };
```

**Comment by atomiks** [comment]
Yeah I agree. The ability to return false from those is not really composable so it's limited to the props hooks only.

**Comment by atomiks** [comment]
I wouldn't recommend monkey-patching as you've done really due to conflicts as you mentioned. It's not [composable - here's a good article as to why](https://overreacted.io/why-isnt-x-a-hook/#a-real-hook-usestate). You might run into weird bugs later on down the track due to it and forget that there's a plugin causing the problem 😭
