### ISSUE TITLE
Do not show if data-tippy-content is empty

### ISSUE THREAD

**Issue by bes-internal** [atomiks/tippyjs#680]
With empty data-tippy-content tooltip looks strange. Let's not show it at all
![image](https://user-images.githubusercontent.com/2046529/72276991-2da8cc80-3642-11ea-829d-057f09643f0b.png)

**Comment by atomiks** [comment]
This is intentional for a few reasons:

- Earlier versions used to not show the tippy, but when forgetting to add content, it led to debugging problems where it seemed like the tippy was simply not being created. This weird tooltip lets you know it's being created, but you forgot the content.
- Performance. You should be using a more specific selector that guarantees content is available – otherwise instances are being needlessly created. `"[data-tippy-content]"` is one such selector that will work.
- You can add placeholder content to let you know when this happens. e.g. `content: "(empty)"` prop when calling the tippy constructor. Or add a `console.warn` in `onCreate` if `instance.props.content` is empty. (This could also be a DEV message we add, but it hasn't been added as of yet.)

**Comment by livevsonline** [comment]
> This is intentional for a few reasons:
> 
>     * Earlier versions used to not show the tippy, but when forgetting to add content, it led to debugging problems where it seemed like the tippy was simply not being created. This weird tooltip lets you know it's being created, but you forgot the content.
> 
>     * Performance. You should be using a more specific selector that guarantees content is available – otherwise instances are being needlessly created. `"[data-tippy-content]"` is one such selector that will work.
> 
>     * You can add placeholder content to let you know when this happens. e.g. `content: "(empty)"` prop when calling the tippy constructor. Or add a `console.warn` in `onCreate` if `instance.props.content` is empty. (This could also be a DEV message we add, but it hasn't been added as of yet.)

Honestly i think that is a bad decision, it is much more functional the old way.

People forgetting to render content imo should not override logical behaviour

You could argue that a HOC or similar is better to not render the Tippy at all if there is no content, however that is a performance issue and not a logical one tied to the behaviour

**Comment by placoderm** [comment]
If anyone ends up here trying to figure out how to fix this when using the React version of Tippy, there is a visible prop:
https://github.com/atomiks/tippyjs-react#visible-boolean-controlled-mode

**Comment by danielpmalagon** [comment]
I came across a situation in which this behavior would be desirable. I have a use case where I show a shortened version of big numbers (e.g 100,000,000 as ≈100 million) dynamically according the value of an input, but should only be shown when numbers are greater than 1000.

I have working the following workaround:

```
.tippy-content:empty {
    display: none;
}

.tippy-content:empty + .tippy-arrow {
    display: none;
}
```

**Comment by Paul-Bob** [comment]
In my use case, the design choice also doesn't make sense but I can understand that there are scenarios where it can save some tedious debugging and some broken keyboards =))

I managed to fix this with the [`onShow` prop](https://atomiks.github.io/tippyjs/v6/all-props/#onshow):

```js
tippy(targets, {
  onShow(instance) {
    if (instance.props.content === null || instance.props.content.length === 0) {
      return false
    }

    return instance
  },
});
```
