### ISSUE TITLE
Delegated tooltip is not positioned correctly when shown with show()

### ISSUE THREAD

**Issue by matthieu60** [atomiks/tippyjs#685]
## Bug description

It looks like when shown using instance.show(), delegated tooltips are positioned according to the element to which they are delegated, and not the real target set with the target prop.

## Reproduction

Here: https://codepen.io/matthieu60/pen/gObQaeg

**Comment by atomiks** [comment]
If you need such behavior, avoid event delegation. It's returning the delegated parents' tippies, so you're showing them instead.

**Comment by glutanimate** [comment]
@atomiks  I'm currently dealing with a use case where I need to use event delegation due to dynamically created targets. Is there any way to programmatically access the tippy children in order to individually show them, or do I have to rethink my approach?

(Sorry to chime in like this, but I thought I'd rather ask here than create a duplicate bug report. Thanks for all your work on tippy, BTW. It's highly appreciated!)
