### ISSUE TITLE
What tippy in v5?

### ISSUE THREAD

**Issue by stratboy** [atomiks/tippyjs#696]
Hi, I come from v2.6.0 and trying the v5. In your docs, it's written

`import tippy from 'tippy.js';`

But there's no tippy.js in the dist directory. So what should I do?

**Comment by atomiks** [comment]
> But there's no tippy.js in the dist directory

I'm not sure what this means? The import syntax is used with module bundlers like webpack, Rollup, or Parcel after you install with a package manager like npm or Yarn. It'll be in your `node_modules` folder.

**Comment by stratboy** [comment]
<img width="854" alt="Schermata 2020-02-06 alle 08 38 03" src="https://user-images.githubusercontent.com/437598/73915629-10bb8e00-48bc-11ea-9bf2-0cb4a2560cea.png">

Yes but there's no 'tippy.js', see attachment. I managed to use tippy.esm.js and it worked.

Also, why is sometimes mentioned tippy.css and some other times backdrop.css? What are they for? What should I use? And the best thing is that tippy seems to work properly even without importing any css.

**Comment by atomiks** [comment]
The filenames have the format embedded in them. `tippy.js` doesn't mean anything without a format, since there's a variety of contexts a user can import the module (script tags, ES modules, CommonJS modules, etc).

The docs should clearly mention `backdrop.css` is for the `animateFill` plugin, can you point to the part that's not clear? I'll edit it.

> And the best thing is that tippy seems to work properly even without importing any css.

It does, but people run into problems without it unless you know all the nuances like `pointer-events`. In v6 I'm aiming to make CSS-less imports work better by putting critical parts on the `style` attribute instead of in CSS (and you can render your own tippy element to use it "headless").

**Comment by stratboy** [comment]
Thank you. Here in 'node vs browser' you only mention backdrop.css and do not specify its usage.

https://atomiks.github.io/tippyjs/getting-started/

I've got another more serious issue, but I'm going to open another thread for that.

**Comment by atomiks** [comment]
I can see how that would be confusing... I'll try to make it clearer

**Comment by atomiks** [comment]
Fixed wording
