### ISSUE TITLE
Singleton usage

### ISSUE THREAD

**Issue by kanalumaddela** [atomiks/tippyjs#700]
I'm currently trying to write a small vuejs wrapper for tippy, but I'm having trouble understanding how the singleton works/is created. Some guidance would be appreciated, preferably a standalone example.

From what I understand looking at the (oudated) [react example](https://github.com/atomiks/tippyjs/blob/079f0316f7759ce54718ea6ca189760afc2b7897/website/src/components/examples/Singleton.js), it seems to be using normal mouse events which change the tippy instance's reference element along with the content? Looking at the latest version of the singleton example is a bit more confusing since it's all abstracted out. I see the `createSingleton`  looks to be a [plugin](https://github.com/atomiks/tippyjs/blob/master/src/addons/createSingleton.ts), but I can't find any docs and/or in depth issues with this.

**Comment by atomiks** [comment]
I think the old React example is super broken and used a flawed technique 

As for the current one — it's still more complex than it needs to be I think and in v6 it's been slimmed down. 

The way it works is you pass an array of tippy instances in, and the singleton will disable all of them because they won't be used (it uses its own instance which you see gets returned at the bottom). It only uses the data from the instances (content + reference elements) 

- `triggerTarget` is the array of reference elements to add event listeners to that will trigger the singleton tippy
- In the `onTrigger` lifecycle, it sets its popperInstance's reference (for positioning) to one of the reference elements that got triggered
