### ISSUE TITLE
CSS performance

### ISSUE THREAD

**Issue by vukvukovich** [atomiks/tippyjs#701]
Hi @atomiks,

Is there some particular reason for using `[data-placement^=right]` instead of `[data-placement=right]`? 

`=` is much faster than `^=`

**Comment by atomiks** [comment]
It supports variation placements like `right-start`. 

I highly doubt CSS selector performance is a problem, the JS (especially Popper's positioning calculations) is almost certainly magnitudes more expensive. Especially since you'll likely only have a few tippy elements max open on the page to be queried by the browser for CSS, making it negligible

**Comment by vukvukovich** [comment]
Thanks, that is why I asked. I've noticed it is working well with `=` too.
