### ISSUE TITLE
Is it possible to make tooltip content hoverable?

### ISSUE THREAD

**Issue by jamesjacobs** [atomiks/tippyjs#709]
After activating a tooltip by hovering on the triggering element you cannot move the mouse cursor over the tooltip content (it closes as soon as the cursor leaves the triggering element), is there a setting or option to make the tooltip persist whilst you hover over the tooltip content and not just the triggering element?

This is a requirement for WCAG 1.4.13: Content on Hover or Focus:

![Screenshot 2020-02-21 at 10 32 00](https://user-images.githubusercontent.com/756393/75026792-72bbec00-5495-11ea-9e54-dca946f61b76.png)

I couldn't see anything in the docs covering this. Potentially achievable with `trigger: manual` and my own event listeners?

**Comment by atomiks** [comment]
`interactive: true`?

**Comment by jamesjacobs** [comment]
Ah, yes that works! Apologies, missed that in the docs. Thanks for the quick response.

**Comment by jamesjacobs** [comment]
It seems using `interactive: true` removes the `aria-describedby` attribute meaning screen readers are unable to read the tooltip.

Is there anyway to keep the `aria-describedby` and allow the tooltip content to be hovered?

Otherwise I can't see a why to make tippy WCAG 2.1 complaint.

**Comment by atomiks** [comment]
Personally I haven't seen that guideline adhered to, even in strongly a11y-focused libraries/design systems. Google apps (YouTube, Gmail, Search, ...), Material-UI, Bootstrap, Reach UI — all of them don't follow that guideline. Personally, I think it comes with an accessibility trade-off for those not using those assistive technology, since it means the tooltip becomes more intrusive than it should be.

If really needed though, you can manually handle it in the `onMount` / `onHide` lifecycles, Tippy gives access to reference element and the instance's `id`.
