### ISSUE TITLE
Add bundle with all css

### ISSUE THREAD

**Issue by woothu** [atomiks/tippyjs#718]
## Problem

Users cannot import all CSS with one import.

## Solution

Please add three build packages:
1. All CSS
2. All themes
3. All animations

When I looked into the source it seemed like package No.1 should be about 4-5kB gzipped. Not a big deal ;)

**Comment by atomiks** [comment]
Separate imports are better for bundle size since they're inherently modular/tree-shakable, and building a full bundle defeats that benefit. It may be easier initially for the consumer, but picking and choosing what you need is better for your users. 4-5 kB may not be too much now but it all adds up, especially for a single-purpose library. It will also increase complexity of the build setup I have which I don't really want to deal with.

**Comment by woothu** [comment]
Of course they are better for bundle size, but one import speed up the development. It would be nice to have choice.

**Comment by omenking** [comment]
Here's my problem I use webpack to build my js but all my css is managed with sprockets in Rails. So I just need to drop in the css into my legacy system, but I have no clue how to get that css file, and now need to goof around trying to compile it from this library.

A single css file, even if it includes what I don't need would be very useful.
