### ISSUE TITLE
Arrow is misspositioned by 1px

### ISSUE THREAD

**Issue by woothu** [atomiks/tippyjs#719]
## Bug description

![image](https://user-images.githubusercontent.com/32914662/75786187-3164ef80-5d65-11ea-9fa6-7e1790f86886.png)

This is probably caused by '-7px' instead of '-8px'
![image](https://user-images.githubusercontent.com/32914662/75786336-683b0580-5d65-11ea-8d1e-b2b71e9e32ce.png)

Repro: 
http://jsfiddle.net/zu7ewLsx/10/

**Comment by atomiks** [comment]
This is actually intentional because of a problem that certain browsers have with zoom — if I made it pixel perfect they have a 1px gap in some cases.

https://github.com/twbs/bootstrap/issues/5349
https://stackoverflow.com/questions/42151106/how-to-prevent-bootstrap-tootip-from-falling-apart

I haven't applied this to translucent theme or svg arrow though, because it causes overlapping issues.

If the problem doesn't exist anymore, I can change it.

**Comment by woothu** [comment]
I have tested this fiddle on 
- edge, 
- firefox,
- chrome,
- safari,
- opera,

and bug I have reported occurs in every one of these browsers

**Comment by KubaJastrz** [comment]
@woothu, if you mean that the arrow is not centered vertically - this seems to be caused by the 1px border on `.tippy-box`.

**Comment by atomiks** [comment]
I'm likely not going to fix the overlapping issue due to zooming gaps (browsers and their rounding... 😖).

For your bordered theme I recommend using the translucent theme as a base, which doesn't have arrow overlapping.

A good method is to use the solid color tooltip (the default) + default CSS arrow if the user has zoomed the page, otherwise you're free to use the translucent theme or SVG arrow if the page is at 100%.  Unfortunately the artifacts are inevitable with the way browsers work, and by default Tippy doesn't suffer from any gaps because of the 1px overlap we use.

For the vertical centering issue, I fixed it in a Popper PR: https://github.com/popperjs/popper-core/pull/1023

Hopefully it'll be released today and I'll release a patch as well to remove the hack I added for the `light-border` theme
