### ISSUE TITLE
Tippy is active, when I leave the site and returned

### ISSUE THREAD

**Issue by inkogn1to** [atomiks/tippyjs#72]
Hello! Very good library, but I've noticed one slight deviation from my desired behavior. And it can be seen even on your site  Example:

1. Open your website https://atomiks.github.io/tippyjs/
2. Click to first button (named: - Default)
3. Open the another tab of your browser
4. Come back to the site https://atomiks.github.io/tippyjs/

After that, you may see, that the Tippy is active agan, although this should not have been...

How I can fix it?

p.s. Sory for my bad english =)

**Comment by atomiks** [comment]
That's because of the `focus` event listener (default trigger is `'mouseenter focus'`). Clicking it makes the ref element receive focus.

Leaving the browser window blurs the element, then coming back makes the element receive focus again which causes the tooltip to show.

Maybe it's fixable, I'm not sure. Any ideas? Maybe you'd need to set up your own detectron to detect when the browser window is blurred (Page Visibility?) and if so do something.

**Comment by atomiks** [comment]
Actually I think it's really easy. I found this: https://github.com/amsul/pickadate.js/issues/160

On hide, I could add `document.activeElement.blur()` (provided the element has a blur method, non-HTMLElements might not.)

**Comment by inkogn1to** [comment]
I did this:

tippy('#resume', {
	hide: function() {
		$(document.activeElement).blur();
	},
});

and it works))

**Comment by atomiks** [comment]
I'm not sure if the library should hook the window blur event (that would make 3 events total :/) or let the developer do it themselves. What do you think? Placing it in the `hide` might cause some issues as I mentioned above...

**Comment by inkogn1to** [comment]
I am only junior developer and I can not tell you how to do it better. But I am looking another libraries of tooltips (for example http://iamceege.github.io/tooltipster/) and there is no such problem...

**Comment by atomiks** [comment]
Their demo page doesn't have the `focus` listener on any of the elements so you can't tell. Their page isn't set up with accessibility in mind it seems.

**Comment by atomiks** [comment]
v1.1.0
