### ISSUE TITLE
createSingleton does not use correct function content in 6.0

### ISSUE THREAD

**Issue by sqal** [atomiks/tippyjs#723]
## Bug description

Hi. There's some regression in createSingleton method when tippy's `content` prop is a function. Please open tippy@6.0 reproduction link and take a look at the console logs. You can see that `content` function is called 4 times but it should be called 3 times (3 tippy instances).  Fourth call receives some ghost div element which isn't even in the DOM which makes the content set to an empty string.

## Reproduction

tippy@5.x - https://jsfiddle.net/uh9aftcm/ 
tippy@6.0 - https://jsfiddle.net/pmwfn41h/

**Comment by KubaJastrz** [comment]
Callstack is leading to these:

https://github.com/atomiks/tippyjs/blob/bbbd40c61ea3c701841e6b14c682780a2db927c4/src/addons/createSingleton.ts#L66

https://github.com/atomiks/tippyjs/blob/bbbd40c61ea3c701841e6b14c682780a2db927c4/src/createTippy.ts#L124

https://github.com/atomiks/tippyjs/blob/bbbd40c61ea3c701841e6b14c682780a2db927c4/src/template.ts#L92

**Comment by KubaJastrz** [comment]
And the bug itself is caused by `createSingleton`'s `onTrigger` hook that receives wrong `instance` (the 4th one, created on empty div with no content) and overrides `content` prop on all previous instances.

![2020-03-04_17-08-00](https://user-images.githubusercontent.com/6443113/75898778-d998b800-5e3a-11ea-8729-6be75b47e4b1.png)
