### ISSUE TITLE
v6 tip will no longer stick on it's trigger element

### ISSUE THREAD

**Issue by stratboy** [atomiks/tippyjs#729]
Hi, I upgraded to v6 from 520, and the tips no longer stay in place when scrolling the page. Please see attachments. This is when scroll == 0:

<img width="511" alt="Schermata 2020-03-08 alle 09 59 50" src="https://user-images.githubusercontent.com/437598/76159746-cbd98000-6123-11ea-99b9-79210a02be94.png">

This happens when page is scrolled a bit:

<img width="530" alt="Schermata 2020-03-08 alle 09 59 58" src="https://user-images.githubusercontent.com/437598/76159758-ea3f7b80-6123-11ea-966e-28209b1ff301.png">

The tip 'follows' the page. How to solve?

By the way, I can't (not able) reproduce the issue on codepen. But thing is, it worked properly with v5.2.0. So maybe you know what's changed between the 2 and thus how to solve/configure so it works again.

Current instance is like this:

```
    const info_tips = tippy('.info-tip',{
      placement: 'top',
      animation: 'shift-away',
      content(reference) {
        const title = reference.getAttribute('title');
        reference.removeAttribute('title');
        return title;
      }
    });
```

Also, 1 thing I've just found out is that if I set `interactive: true` it will work properly. But probably that's not the best way to solve the issue. Also, if setting `interactive: true`, the tips will no longer maintain the content text in one line. It will wrap. Not so good in my case:

<img width="259" alt="Schermata 2020-03-08 alle 10 12 05" src="https://user-images.githubusercontent.com/437598/76159895-4951c000-6125-11ea-8fa5-7548e6030a4a.png">

**Comment by atomiks** [comment]
I think that might be this https://popper.js.org/docs/v2/faq/#why-is-my-popper-in-the-wrong-location-or-not-visible-at-all

**Comment by stratboy** [comment]
Thank you, but that's not my case:
<img width="592" alt="Schermata 2020-03-08 alle 16 49 48" src="https://user-images.githubusercontent.com/437598/76166208-20e5b800-615d-11ea-8675-2d6c0b0901e8.png">


``

**Comment by atomiks** [comment]
Does it happen if disabling `adaptive`?

```js
popperOptions: {
  modifiers: [
    {
      name: 'computeStyles',
      options: {adaptive: false} 
    }
  ]
}
```

**Comment by stratboy** [comment]
Yes. Just tried it, it doesn't solve. Currently, the only way to avoid the issue is to set interactive to true, with the reported drawbacks.

**Comment by atomiks** [comment]
`interactive: true` appends the tippy to the parent node of the reference element, which is why that's happening (there must be a specified width set on the parent which constrains the tippy's width to it), but it shouldn't happen anyway. I haven't seen this happen and hasn't been reported in Popper v2, so it must be something else causing it.

Without a reproduction I can't help though. The bug not happening in CodePen might be due to the fact that it's in an `<iframe>` which works differently to the top-most `<body>`.

If you can, minimally reproduce it in a pure `.html` file (not CodePen due to the above problem)
