### ISSUE TITLE
Lots of tooltip with infinite scroll

### ISSUE THREAD

**Issue by obsidienne** [atomiks/tippyjs#79]
Hi,

My website is a song database. Each songs have 3 types of opinion (up / like / down). With that system, our DJs can give their opinions. When a use click give it's opinion, i update the title.
The website uses turbolinks to ensure a continued audio play. So my tippy instance is not destroyed during navigation.

My problem are:
- auto update of title (but they are already a bug on that)
- append to an existing Tippy instance, the new songs added by the infinite scroll. I can destroy but not add a tooltip to an existing instance.

I would like to do : tip.add("CSS selector")

Is there a good way of doing that ?

thanks

**Comment by atomiks** [comment]
Is there a reason why you can't just make a new instance with the same settings?

**Comment by obsidienne** [comment]
Hi,
Maybe, i'm misusing the lib.

Turbolinks implies that every JS objects stay alive accros navigation
turbolinks:load event is the equivalent of the load event. And i use it to init tippy with a ```new Tippy(".tippy")```. 

I use tippy to show the users name liking/disliking the song.
When the user gives is opinions (like/dislike), I do an Ajax call and change the title, when the user scroll I add new songs and need to init Tippy for those new songs and those new title.
I use the destroyAll() but, i have the previous tooltip still displaying with the new tooltip.

**Comment by obsidienne** [comment]
I'm not sure 100% but I think the problem lies in this line of Turbolinks doc

> When possible, avoid using the turbolinks:load event to add event listeners directly to elements on the page body. Instead, consider using event delegation to register event listeners once on document or window.

CreateTrigger in Tippy.js does not use event delegation. Maybe it's the problem.

**Comment by atomiks** [comment]
You can just do `tippy('.tippy')` again and it won't have an effect on existing ones since the `title` attribute gets removed. Even better, `tippy('.tippy[title]')`

I've used it briefly on a project with infinite scroll and did the above and didn't have any problems.

**Comment by obsidienne** [comment]
Yes, sure. ```tippy('.tippy[title])``` is better. I have changed it. 

But the difficulty is more on turbolinks. When turbolinks do a visit (follow a link or restore a previous page). It changes the content of the body. It does not replace it. 
So when the user navigate the site, new tippy() stays in memory so does its appendTo reference. Which is the previous <body>

**Comment by obsidienne** [comment]
Ok, using ```new tippy('.tippy[title]',{appendTo: document.body});```

The function init() is called one time (in case of turbolinks) but the body changes each time and the reference not. 

Resolve one of my bugs.

**Comment by obsidienne** [comment]
A reset() function, resetting the state like it is a fresh load will simplify the turbolinks uses. 

Can you help me create one ?

**Comment by daveybrown** [comment]
Hey, check out the destroyAll [method](https://atomiks.github.io/tippyjs/#methods).

**Comment by obsidienne** [comment]
Nop, destroyAll does not reset the state of tippy. The proof, if I destroyAll and recreate the tooltips. The counter does not start at one.

**Comment by obsidienne** [comment]
The init is not relaunch too, the store is not emptied.

**Comment by daveybrown** [comment]
Out of interest, why do you need to reset the counter?

**Comment by obsidienne** [comment]
I don't really care about the store. It's more to show that destroyAll does not reset Tippy state.

I'm looking in a combination of destroyAll()/new tippy('.tippy[title], {appendTo: document.body})

**Comment by atomiks** [comment]
I'm not 100% sure what you mean, but if I'm understanding correctly, your problem is that the `document.body` element is replaced by Turbolinks, which means the `init()` function (which sets the `appendTo` setting's default) doesn't have the correct element to append to?

Each nav change/body replace you might be able to do `tippy.Defaults.appendTo = document.body`, or manually add the option in the object as you're doing. So what is the problem exactly?

**Comment by padi** [comment]
First of all, nifty tool you've got @atomiks.

I'd like to contribute to the discussion since I tackled a similar turbolinks issue.

I think what @obsidienne is referring to is to be able to "reset" to a state before any of Tippy.js has been applied to the DOM (i.e. no Tippy instance has been created nor any DOM mutation). This is a pretty common feature in any javascript plugin. Here are some examples:

Select2: https://select2.github.io/examples.html#programmatic

```javascript
// create select2; requires jQuery
var $example = $(".js-example-programmatic").select2();

// bind to a button that destroys the select2 and returns/cleans the select tag to it's pre-select2 state
$(".js-programmatic-destroy").on("click", function () { $example.select2("destroy"); });

// This is the important part that's not exactly* present in tippy.js:
// being able to reenable select2 with the same default/no settings during 'tubrolinks:load'
var $example = $(".js-example-programmatic").select2();
```

Here's a similar library, something that shows up a calendar tooltip of sorts, Flatpickr: https://chmln.github.io/flatpickr/instance-methods-properties-elements/#destroy

```javascript
flatpickr("#myInput", {}); // invocation without saving to a var
// ...

// Here's one feature I really like, not having to save to a variable to get to the instance, and
// simply cleanup the flatpickr instance.
document.querySelector("#myInput")._flatpickr.destroy();

// This is the important part that's not exactly* present in tippy.js:
// being able to reenable flatpickr with the same default/no settings during 'tubrolinks:load'
flatpickr("#myInput", {});
```

Compare this to the current tippy.js workaround:

```javascript
  var tippyButton = document.querySelectorAll('.btn');
  tippy(tippyButton);
  
  // during turbolinks:load
  // either:
  tippy(tippyButton,  {appendTo: document.body});
  // or 
  tippy.Defaults.appendTo = document.body // update to 'current' document.body
  tippy(tippyButton);
```

\* While I did observe that `.destroyAll()` removes the tippy-related classes and data-* attributes, now you cannot do a simple `tippy(tippyButton)`.

Why do I think that the current workaround is an issue?

We now ***require*** the tippy.js consumer to be aware of where the popper is being appended to, which is kind of a leaky abstraction considering I just wanted to just show the most basic tippy tooltip (no options). 

What can I propose for this? Two solutions:

1. Have a "Caveats" section in the Wiki/docs. The current `tippy.Defaults.appendTo = document.body` is kind of ok to me if it can be made more obvious that:
  -  you can set defaults with `tippy.Defaults`
  - you can set where the tooltips are being appended with `tippy.Defaults.appendTo`.

2. If `appendTo` can also accept functions that evaluate the element unto which tooltips are attached e.g. https://github.com/atomiks/tippyjs/blob/2278dcbf56c5a3ec61022c0e5f578f69baedcc01/src/js/core/init.js#L13

```
Defaults.appendTo = function() { document.body }
```

**Comment by padi** [comment]
Here's a working example I've whipped up for you: https://turbolinks-tippy.herokuapp.com/

It's a newly generated Rails app with tippy installed via yarn. The file of interest is this
https://github.com/padi/turbolinks-tippy-example/blob/master/app/assets/javascripts/application.js

**Comment by atomiks** [comment]
@padi nice comment!

The function idea is interesting. It somewhat reminds me of Vue's `data()` in components being a function to return a new fresh object for each new instance.

For tippy, we can grab the "current"/fresh body element by invoking a function instead of saving the first one when `init()` is called for the first time.

So essentially 

```javascript
Defaults.appendTo = () => document.body
```

Then each time we need `appendTo`, we invoke it like `appendTo()` instead to grab the current body element.

**Comment by padi** [comment]
Yup, that's what I thought. I'm not that acquainted with ES6 yet as I've only recently started learning Webpack + Vue + ES6, but I can sort of understand/infer what's going on while I was reading the source code. 👍  Fat arrows indeed.

**Comment by atomiks** [comment]
Yeah ES6+ is great, I began learning it this year also. In fact this project has been the main source of my JS learning for the last few months in general 😄

**Comment by padi** [comment]
Let me try to hack this up a bit and see if I can easily get this through.

I see that there are tests in tests/spec. How do I run them?

**Comment by atomiks** [comment]
`npm test`

If you have trouble msg @artyomtrityak as he just recently set that up in the past week and I'm not too familiar with it.

**Comment by atomiks** [comment]
I believe the appendTo option would have fixed this?

**Comment by obsidienne** [comment]
Yes, it resolves my bug. 
Thanks a lot
