### ISSUE TITLE
Event handlers aren't properly removed when destroyed

### ISSUE THREAD

**Issue by vladjerca** [atomiks/tippyjs#824]
## Bug description

After `destroy`-ing an event delegated instance, about ~95%~ 12 of event handlers created still remain attached.

It seems that most events aren't cleared when destroying the instance and I also suspect that some of them come from `popper` but I know for sure that a lot are also left out from `tippy` as well.

I'm not a big fan of relying on GC to handle event listeners for me, it was very easy to bring the memory utilization from 30 to 100 MB (on this example) just hovering around, and after 5 minutes of idle time it dropped to 90MB.

## Reproduction

StackBlitz Code Editor: https://stackblitz.com/edit/tippyjs-memory-leak?file=index.ts
StackBlitz Demo: https://tippyjs-memory-leak.stackblitz.io/

**Comment by atomiks** [comment]
Not sure I can repro/confirm this. Are you sure the `EventLeakObserver` doesn't have a bug in it?

`getEventListeners()` API on the child node shows that no event listeners are left on the child that had an instance created for it after destroying the delegate instance. They don't double up either.

<img width="569" alt="Screen Shot 2020-07-29 at 3 04 21 pm" src="https://user-images.githubusercontent.com/22450188/88758856-d7017b00-d1ac-11ea-9cfb-10c70586d280.png">

As for GC, not sure how it gets cleaned up otherwise by the browser.

**Comment by vladjerca** [comment]
@atomiks That's a very good point 🤔 I'll update the link with the `dedupe` in mind.

https://stackblitz.com/edit/tippyjs-memory-leak-with-dupe-skipping?file=index.ts

So yes, it's true it wasn't I bad as I made it out to be 🤣 but there are still 14 listeners attached after it's destroyed. Maybe global listeners?

**Comment by atomiks** [comment]
> touchstart on document
> blur on window

These are expected

> mouseenter / mouseleave on every div#tippy-n where n = [1, 5]

I think these are on the `popper` element. GC should clean these up once the tippy instance reference gets freed I believe

**Comment by vladjerca** [comment]
@atomiks theoretically they should be picked up by the GC, but it really depends on if the handlers reference anything inside 🤔 (that's really why I don't usually like relying on the GC for these things as there will always be a big `if` associated).
