### ISSUE TITLE
interactiveBorder is not working with virtual references when offset is set.

### ISSUE THREAD

**Issue by deevannaveed** [atomiks/tippyjs#893]
## Bug description

The problem is that I am using virtual references using `getReferenceClientRect` and I want the tippy to have interactive border so that if I move my mouse towards the tippy popup it should stay there instead of moving, if I remove the offset its working but I need the offset with interactive border. 

## Reproduction

CodePen link: https://codepen.io/deevannaveed/pen/ExgMRbm

**Comment by KubaJastrz** [comment]
I'm not sure if I understand you fully. I get that you want your tooltip to be interactive, ie. allow the tooltip to stay in-place instead of following the mouse cursor. But you are explicitly setting the tooltip position on mousemove event.

Maybe some kind of throttling on the mousemove event could help you? Or maybe do you want the tooltip to become interactive after you stop moving the mouse cursor for X amount of time?

**Comment by deevannaveed** [comment]
> Maybe some kind of throttling on the mousemove event could help you? Or maybe do you want the tooltip to become interactive after you stop moving the mouse cursor for X amount of time?

In the codepen example if you remove offset from the tippy we can easily move over the tippy and we can interact with the button event its following the cursor but if we add offset then we cannot move easily towards the tippy we must move our mouse very fast towards the tippy to interact with the button.

**Comment by atomiks** [comment]
This is kind of just a UX problem, as @KubaJastrz said, the code you've written is making the tippy follow the mouse cursor which means it's constantly trying to avoid it, the only reason you can 'land' on it occassionally is because of the way the browser registers the mousemove events with debouncing or whatever. I thought the `followCursor` plugin handled this but maybe not for "free move" tippys like this one.
