### ISSUE TITLE
Update Popper.js version

### ISSUE THREAD

**Issue by CaitlinWeb** [atomiks/tippyjs#93]
I encountered an issue with positioning of the tooltip on mobile. It was sticking the tooltip at the bottom of the initial viewport for elements further down the page. 

I tried `tippy.standalone.js` with the newest version of Popper.js (1.12.5) and that resolved it. You may want to update to the newest version of Popper for the packaged files.

**Comment by atomiks** [comment]
I'm looking at using 1.12.4 for the next bundle instead of .5 until an issue regarding position updating can be resolved. You may encounter some problems with 1.12.5 when the element moves close to the viewport boundaries and you show the tooltip again -- it won't be fully in view. 

But yeah it'll be updated in the next release soon... preferrably with both of those issues fixed.
