### ISSUE TITLE
Tooltips position incorrect css display: contents

### ISSUE THREAD

**Issue by kocoten1992** [atomiks/tippyjs#952]
## Bug description

Using `display: contents`, tippyjs tooltip position always top left of the screen.

## Reproduction
https://codepen.io/kocoten1992/pen/mdWQGrz

**Comment by graemechapman** [comment]
I've just encountered this too - the problem seems to be that `getBoundingClientRect` (as well as any other position based properties) returns all zero values for an element with `display: contents`. 

I have a partial workaround, but it only works if the element has child elements - https://codepen.io/Graemec/pen/XWRNaBq

**Comment by atomiks** [comment]
This is a bug for Popper positioning engine => https://github.com/popperjs/popper-core
